server:
  contextPath: /blogs
  port: 8081

spring:
  jpa:
    show-sql: true

---
spring:
  profiles: dev
    datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/blogs
      username: root
      password: root

security: 
	  user:
	    name: blog
	    password: blog123
---