server:
  contextPath: /blogs
  port: 8081

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true

---
spring:
        profiles: dev
        datasource:
        	url: jdbc:mysql://localhost:3306/blogs
        	username: root
        	password: root

---

